### ISSUE TITLE
Retrieving and querying variants from the REST API

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#186]
Hi PGS Catalog Team

This is a feature request.

It would be really nice to have a way of retrieving scores by variant identifiers (`variant_id`), and the reverse, to get variant identifiers by score ids (`pgs_id`):

- `/rest/variant/search?pgs_id=PGS000001`
- `/rest/score/search?variant_id=rs123213`

As I understand it, currently, there is no way of finding these relationships between variants and scores in the metadata. So, to find this information, we have to download all PGS scoring files and look in there.

I understand though that you'd probably need to fix https://github.com/PGScatalog/PGS_Catalog/issues/150 before implementing such a feature.

**Comment by smlmbrt** [comment]
This is probably something we won't implement because:
- Holding variant information in the DB would make it very large (costly), and slow
- Usually people don't select which PGS to use based on the set of variants in the score (sometimes the select by the # of variants which we expose in the API), as their inclusion is dependant on gentoyping/imputation and LD. This might be relevant if you want to see how variant weights change between different scores, but in that way you've probably already downloaded the scores and can compare on ID/position matches. The variant lookup does make sense for GWAS Summary Statistics to see if a variant was included in a study and it's association, but in the PGS it doesn't really have the same meaning and shouldn't be interpreted the same. 

We're happy to reevaluate if there is a common use case you think this would enable!

**Comment by ramiromagno** [comment]
Hi @smlmbrt 

Thanks for your quick reply.

The use case I was thinking about was the case where perhaps you would like to know the relative weight (weight divided by the sum of abs. of the weights) of a variant across PGSs... in a kind of meta-analysis type of manner... but I see that it might be too much of a specific use case and not worth the trouble.

**Comment by smlmbrt** [comment]
I think that would be of interest to some doing a deep-dive on a specific set of scores for a trait, but I don't think it's something that needs to be included in the DB because they'd have already selected the scores they're interested in.

**Comment by ramiromagno** [comment]
Fair enough!
