### ISSUE TITLE
Question about `/rest/trait/search` with `include_children=1`?

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#212]
Do I understand it correctly that although the endpoint `/rest/trait/search` allows for inclusion of child traits with `include_children=1`, in reality is not possible to tell apart the traits that are direct matches of the queries, and which ones are children thereof.

Instead, would it not be possible to make `/rest/trait/search` return `EFOTrait_OntologyChild` responses, like the endpoint `/rest/trait/{trait_id}` does?

**Comment by smlmbrt** [comment]
Correct, but I think this is the ideal behaviour. The purpose of this endpoint is to find a list of traits that match your search terms/criteria, not to expose the structure of those terms in the ontology (parent/child relationships). For that it makes more sense to interrogate each term with the `/rest/trait/{trait_id}` endpoint.

The point of the include_children flag is to get EFO terms that might not have directly matching synonyms but are definitely related. For instance `breast carcinoma` ([EFO_0000305](https://www.pgscatalog.org/trait/EFO_0000305/)) isn't returned in the `/rest/trait/search?term=breast%20cancer&exact=0&include_children=0` query but is in the `/rest/trait/search?term=breast%20cancer&exact=0&include_children=1` results because it doesn't have _breast cancer_ as a synonym/label but it does have a parent with that term. In this way the behaviour of this endpoint makes sense as-is and wouldn't result in child terms being duplicated as results of the query and in the return of child terms in multiple parent terms. 

Adding more of a description to the schema regarding its purpose is probably the best way to resolve this.

**Comment by ramiromagno** [comment]
Okay, thanks for the explanation Sam!
