### ISSUE TITLE
Potential bug with annotation trait URI : Ischemic stroke

### ISSUE THREAD

**Issue by spiros** [PGScatalog/PGS_Catalog#249]
The PGS traits dataset (`pgs_traits_data.csv`) entry for ischemic stroke (http://purl.obolibrary.org/obo/HP_0002140) is, I think, malformed and contains 

The current value is "https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http://purl.obolibrary.org/obo/HP_0002140"

Whereas it should be "http://purl.obolibrary.org/obo/HP_0002140"

**Comment by smlmbrt** [comment]
Thanks for your comment @spiros, this will get corrected in the next release!

I think we originally had all of the external IDs like this so that they would link back to the copy of the term in the Experimental Factor Ontology (EFO) where we source the term definition and parent/child linkages. I wonder if we should consider adding a separate `EFO URL` field to capture this?

**Comment by spiros** [comment]
Hm good question, not sure what the best approach is - I've seen it both
ways i.e. sometimes the EFO_URL contains non-EFO URIs in there, and
sometimes they are separated...!

**Comment by smlmbrt** [comment]
#250 corrected the URL so it should be the purl ID in the current and all future releases.
