### ISSUE TITLE
Search by SNP Not Available

### ISSUE THREAD

**Issue by DarioS** [PGScatalog/PGS_Catalog#366]
While showing the catalogue to a clinician, he mentioned it would be handy to search by rsID. Not sure if that is within your scope.

**Comment by smlmbrt** [comment]
Hi @DarioS, we don't allow searching by rsID because the presence or absence of a variant in a PGS is non-informative. As example, you could look up a strongly-associated rsID for a trait and it might not be in the best score - this isn't because it isn't a strongly associated variant, it's more likely that another variant in LD is included (or the variant was excluded for some reason to do with the computational method used to develop the score). The GWAS Catalog remains the best way to search for rsID associations with disease (http://ebi.ac.uk/gwas).
